### ISSUE TITLE
Transfer to haskell-perf

### ISSUE THREAD

**Issue by fishtreesugar** [haskell-perf/bytestring-builders#3]
I think [haskell-perf](https://github.com/haskell-perf) is a great place to host this project, would you hope to do this?

**Comment by nikita-volkov** [comment]
Makes sense.

@chrisdone, care to take me in?

**Comment by chrisdone** [comment]
Sure!

**Comment by nikita-volkov** [comment]
Done.

@chrisdone Thanks. Can I get the privilege to edit the repository's settings?

**Comment by chrisdone** [comment]
Yep, changed to Admin.
